name: Build and Deploy to EC2

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with maven
        run: mvn clean install

      - name: Login docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: docker build -t bielxrd/authdocs:latest .

      - name: Docker push
        run: docker push bielxrd/authdocs:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull bielxrd/authdocs:latest
            docker stop authdocs || true
            docker rm authdocs || true
            docker run -d \
             -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
             -e DATABASE_USER=${{ secrets.DATABASE_USER }} \
             -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
             --name auth-docs -p 8080:8080 bielxrd/authdocs:latest
          EOF