name: Build and Deploy to EC2

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Set environment variables
        run: |
              echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
              echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> $GITHUB_ENV
              echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> $GITHUB_ENV

      - name: Build with maven
        run: mvn clean install

      - name: Login docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Set environment variables
        run: |
              echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
              echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> $GITHUB_ENV
              echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> $GITHUB_ENV

      - name: Docker build
        run: docker build -t bielxrd/authdocs:latest .

      - name: Docker push
        run: docker push bielxrd/authdocs:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create SSH key file
        run: |
            echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
            chmod 600 ec2_key.pem

      - name: Deploy to EC2
        run: |
            ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
              docker pull bielxrd/authdocs:latest &&
              docker stop authdocs || true &&
              docker rm authdocs || true &&
              docker run -d -p 8080:8080 -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e DATABASE_USER=${{ secrets.DATABASE_USER }} -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} --name auth-docs bielxrd/authdocs:latest
            EOF

      - name: Clean up
        run: rm ec2_key.pem